### ISSUE TITLE
Consider using enumerate instead of iterating with range and len

### ISSUE THREAD

**Issue by trm187** [PRIS2/Psi#3]
#### Occurred on:
+ **Commit**:  0107c2a10f61bee25b329e2ddd8f725e52e3abfb
+ **File**:    [src/polynomial.py](https://github.com/PRIS2/Psi/blob/0107c2a10f61bee25b329e2ddd8f725e52e3abfb/src/polynomial.py)
+ **LineNum**: [70](https://github.com/PRIS2/Psi/blob/0107c2a10f61bee25b329e2ddd8f725e52e3abfb/src/polynomial.py#L70)
+ **Code**:    `for i in range(0, len(short_list)):`

    
#### Currently on:
+ **Commit**:  251ba4655d3ceb0e0abcad6412136629415cc1a1
+ **File**:    [src/polynomial.py](https://github.com/PRIS2/Psi/blob/251ba4655d3ceb0e0abcad6412136629415cc1a1/src/polynomial.py)
+ **LineNum**: [73](https://github.com/PRIS2/Psi/blob/251ba4655d3ceb0e0abcad6412136629415cc1a1/src/polynomial.py#L73)

**Comment by luxor-g** [comment]
Por partes, lo que dice codacy ("Consider using enumerate instead of iterating with range and len") es que use `for i in list` pero en este caso no puedo porque accedo a dos listas a la vez y para eso necesito el index. Por otro lado, tu comentas que "Sería mejor sustituir el rango del for por una variable por si cambia la longitud de la lista que usas" pero yo no estoy haciendo cambios sobre ninguna array sobre la que estoy iterando, como vemos: `result.monomials.append(short_list[i] + long_list[i])` solo estoy sumando las array y añadiendo al resultado. Además, ya me he asegurado previamente que todas las arrays tengan la misma longitud.
